<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="IBM-Testing04" name="Admin_home.TestLoanGrant" tests="29" failures="0" timestamp="9 Jul 2018 11:23:25 GMT" time="119.553" errors="4">
  <testcase name="account" time="14.041" classname="Admin_home.TestLoanGrant"/>
  <testcase name="otherDetailForLoan" time="0.276" classname="Admin_home.TestLoanGrant"/>
  <testcase name="ChangePasswordForMember" time="2.591" classname="Admin_home.TestLoanGrant"/>
  <testcase name="checkAppDetail" time="0.932" classname="Admin_home.TestLoanGrant"/>
  <testcase name="backNevigationForMemberModify" time="11.191" classname="Admin_home.TestLoanGrant"/>
  <testcase name="disableExpire" time="5.552" classname="Admin_home.TestLoanGrant"/>
  <testcase name="removeAdvertisment" time="1.265" classname="Admin_home.TestLoanGrant"/>
  <testcase name="adModule" time="2.042" classname="Admin_home.TestLoanGrant"/>
  <testcase name="clickPayment" time="2.076" classname="Admin_home.TestLoanGrant">
    <error type="java.lang.AssertionError" message=" it showing more then &#039;Debit to member&#039; list  expected [Debit to member] but found [Community to member]">
      <![CDATA[java.lang.AssertionError:  it showing more then 'Debit to member' list  expected [Debit to member] but found [Community to member]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at Admin_home.AccountModule.clickPayment(AccountModule.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- clickPayment -->
  <testcase name="loanPageAfterClickSubmit" time="3.368" classname="Admin_home.TestLoanGrant"/>
  <testcase name="jumpToMemberProfile" time="10.101" classname="Admin_home.TestLoanGrant"/>
  <testcase name="submitButton" time="3.802" classname="Admin_home.TestLoanGrant"/>
  <testcase name="addNewAd" time="5.159" classname="Admin_home.TestLoanGrant">
    <error type="java.lang.AssertionError" message="the valu of title must take 4 to 25 but it take more then 25 expected [25] but found [45]">
      <![CDATA[java.lang.AssertionError: the valu of title must take 4 to 25 but it take more then 25 expected [25] but found [45]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at Admin_home.AdvertisementsManage.addNewAd(AdvertisementsManage.java:81)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- addNewAd -->
  <testcase name="affterCommentClickToSubmit" time="6.625" classname="Admin_home.TestLoanGrant"/>
  <testcase name="viewLoan" time="3.470" classname="Admin_home.TestLoanGrant"/>
  <testcase name="browserLunch" time="6.861" classname="Admin_home.TestLoanGrant"/>
  <testcase name="accoutInfo" time="2.343" classname="Admin_home.TestLoanGrant"/>
  <testcase name="modifyMemberProfile" time="1.898" classname="Admin_home.TestLoanGrant">
    <error type="java.lang.AssertionError" message="expected [40] but found [86]">
      <![CDATA[java.lang.AssertionError: expected [40] but found [86]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at Admin_home.MemberProfileModify.modifyMemberProfile(MemberProfileModify.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- modifyMemberProfile -->
  <testcase name="loanPage" time="5.465" classname="Admin_home.TestLoanGrant"/>
  <testcase name="accountName" time="2.261" classname="Admin_home.TestLoanGrant"/>
  <testcase name="afterPayType" time="0.538" classname="Admin_home.TestLoanGrant"/>
  <testcase name="datePassing" time="2.575" classname="Admin_home.TestLoanGrant"/>
  <testcase name="moreDetail" time="0.337" classname="Admin_home.TestLoanGrant"/>
  <testcase name="historyTab" time="0.068" classname="Admin_home.TestLoanGrant"/>
  <testcase name="modifyAdvertisment" time="16.365" classname="Admin_home.TestLoanGrant"/>
  <testcase name="submit" time="3.251" classname="Admin_home.TestLoanGrant"/>
  <testcase name="getHistoryTable" time="2.505" classname="Admin_home.TestLoanGrant"/>
  <testcase name="loginDetail" time="2.138" classname="Admin_home.TestLoanGrant"/>
  <testcase name="loanDetail" time="0.457" classname="Admin_home.TestLoanGrant">
    <error type="java.lang.AssertionError" message="expected [10] but found [11]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [11]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at Admin_home.TestLoanGrant.loanDetail(TestLoanGrant.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- loanDetail -->
</testsuite> <!-- Admin_home.TestLoanGrant -->
